import = ["/home/etienne/.config/alacritty/colors.toml"]

[font]
size = 12.0

[font.normal]
family = "Fira Code"

[window]
opacity = 0.9

[window.dimensions]
columns = 200
lines = 50

[window.padding]
x = 5
y = 5
